import type {CurriculumQuestion} from "./curriculum.ts";
type Item=Omit<CurriculumQuestion,"token">&{passage?:string};
const q=(prompt:string,a:string,b:string,c:string,explanation:string,passage?:string):Item=>({prompt,options:[a,b,c],answer:0,explanation,passage});

export const LEVEL4_QUIZ_SETS:Item[][]=[
 [q("Which word is the root of helpful?","help","helpful","ful","Help carries the main meaning."),q("Remove -ing from sailing.","sail","sa","sailing","Sail remains."),q("Which word grows from the root play?","player","plate","place","Player contains play."),q("Find the shared root in teacher and teaching.","teach","each","her","Teach is shared."),q("Build a word meaning someone who reads.","reader","readful","reread","Reader names a person who reads.")],
 [q("Join rain and coat.","raincoat","rain coatly","coatrain","Raincoat is a compound word."),q("Which compound names a place for books?","bookshelf","bookfish","shelfful","Bookshelf combines book and shelf."),q("Split playground correctly.","play + ground","pla + yground","player + ground","Play and ground make playground."),q("A bright beam from the sun is a ___.","sunbeam","sunboat","beamful","Sunbeam combines sun and beam."),q("Which pair forms classroom?","class + room","clap + room","class + broom","Class and room form classroom.")],
 [q("Add un- to happy.","unhappy","rehappy","happyful","Unhappy means not happy."),q("Which prefix makes pack mean pack again?","re-","un-","-er","Repack means pack again."),q("Complete: The untied rope is ___ tied.","not","again","very","Un- can mean not."),q("Which word means return to read?","reread","unread","reader","Reread means read again."),q("Choose the correct prefix for unsafe.","un-","re-","-less","Un- changes safe to not safe.")],
 [q("Add -ful to care.","careful","careless","recare","Careful means showing care."),q("Which word means without fear?","fearless","fearful","refear","-less means without."),q("Turn quick into a word describing an action.","quickly","quicker","quickful","Quickly tells how."),q("A person who paints is a ___.","painter","paintly","paintless","-er can name a person."),q("Which ending makes kind into a noun?","kindness","kindful","unkind","Kindness names the quality.")],
 [q("Which word has ea like sea?","clean","bread","head","Clean has the long-e sound."),q("Find ea with the sound in bread.","head","beach","dream","Head shares the short-e sound."),q("Complete the island word: b__ch.","beach","batch","bench","Ea completes beach."),q("Which pair has matching ea sounds?","team — dream","sea — head","clean — bread","Team and dream share long e."),q("The class will ___ a reef fact aloud.","read","road","red","Read fits and uses ea.")],
 [q("Which opening clearly introduces a discussion?","Let us talk about keeping our beach clean.","Clean because beach.","Yesterday maybe blue.","The first line states the topic."),q("What should a listener ask when a point is unclear?","Could you explain that again?","Is lunch ready?","I will not listen.","The question requests clarification."),q("Choose the formal greeting for a school visitor.","Good morning, welcome to our class.","Hey, you there!","Move away.","The first greeting is respectful."),q("Which response builds on a classmate’s idea?","I agree, and we could add bins.","Your idea is silly.","I was not listening.","It connects respectfully."),q("End a short presentation appropriately.","Thank you. Do you have a question?","That is it, bye maybe.","Start listening now.","The first closing invites questions.")],
 [q("A poster says ‘SAVE OUR REEF’ above a turtle. What is its purpose?","encourage reef care","tell a bedtime story","list lunch choices","The poster calls for action."),q("Which feature makes an advertisement easy to notice?","a bold heading","a hidden title","a long unbroken paragraph","A bold heading attracts attention."),q("Choose a caption for a photo of pupils planting palms.","Our class plants shade trees.","A dhoni crosses deep water.","Three fish hide in coral.","The caption matches the photo."),q("A map arrow points north. What does it help a reader do?","find direction","hear dialogue","identify a rhyme","Map arrows show direction."),q("Which slogan suits a reusable bottle?","Refill today, protect our sea!","Throw it away each day!","Books belong on palms!","The slogan supports reuse.")],
 [q("Read: ‘The jetty was wet. Dark clouds covered the sky. Hassan opened his umbrella.’ What is the main point?","Rain was arriving.","Hassan bought a jetty.","The sky was sunny.","The details signal rain.","The jetty was wet. Dark clouds covered the sky. Hassan opened his umbrella."),q("Which detail best supports ‘The beach was busy’?","Children played while boats arrived.","One shell lay still.","Night was quiet.","Many actions show a busy beach."),q("Choose the best summary of three lines about cleaning litter.","The class worked together to clean the shore.","A bag was blue.","Aminath wore sandals.","The summary captures the big idea."),q("Which sentence is an unimportant detail in a paragraph about turtle nests?","The guide wore a red cap.","Turtles bury eggs in sand.","The nests need protection.","The cap does not explain nests."),q("What should a good summary leave out?","small unrelated details","the central idea","the key result","A summary keeps key information.")],
 [q("Both stories happen at the harbour. What is the shared feature?","setting","problem","caption","Harbour is the setting."),q("Story A ends with a found bag; Story B ends with a repaired net. What differs?","the solutions","the island","the language","The endings solve different problems."),q("Which word signals a comparison?","both","because","first","Both identifies a similarity."),q("Choose a sentence that contrasts two events.","Ali sailed, but Mariyam stayed ashore.","Ali and Mariyam sailed.","First Ali sailed.","But shows a difference."),q("A chart gives 8 fish on Monday and 5 on Tuesday. Which comparison is correct?","Monday has three more fish.","Tuesday has three more fish.","The totals are equal.","Eight is three more than five.")],
 [q("Which heading belongs above facts about a dolphin’s food?","What Dolphins Eat","Where We Went","My Funny Ending","The heading groups food facts."),q("Why does a report use subheadings?","to group related facts","to hide the topic","to create dialogue","Subheadings organize sections."),q("Bold text usually tells readers to ___.","notice an important word","skip the sentence","read backwards","Bold type draws attention."),q("Choose the best order for report sections.","Title — Habitat — Food — Body","Food — Goodbye — Once upon a time","Problem — Joke — Address","The first order groups information."),q("Where would ‘It sleeps in shallow caves’ belong?","Habitat","Food","Title","The detail describes where it lives.")],
 [q("Which group forms a complete paragraph topic?","Reef fish need safe homes.","Because coral.","Blue quickly swims.","The first is a complete topic sentence."),q("Add a supporting detail to ‘Dhonis help island communities.’","They carry people and supplies.","My pencil is yellow.","Yesterday was Tuesday.","The detail explains how dhonis help."),q("Choose a closing sentence for a palm-tree paragraph.","For these reasons, palms are useful island trees.","First I woke up.","Where is the ruler?","The line wraps up the topic."),q("Which sentence does not belong in a paragraph about school gardens?","A tuna swims beyond the reef.","Pupils water young plants.","Teachers collect dry leaves.","The tuna detail changes topic."),q("Arrange paragraph parts logically.","topic — details — closing","closing — title — question","detail — greeting — address","A paragraph develops from topic to close.")],
 [q("Vary the start of ‘I walked to the jetty.’","After breakfast, I walked to the jetty.","I I walked to the jetty.","Because walked jetty.","The time phrase varies the opening."),q("Which sentence begins with a place phrase?","Beside the lagoon, a heron waited.","The heron waited beside the lagoon.","A heron is a bird.","Beside the lagoon opens the sentence."),q("Choose a sentence beginning with an action.","Splashing loudly, the fish crossed the pool.","The fish crossed the pool.","Blue fish pool.","Splashing loudly creates an action opening."),q("Which beginning best builds interest?","Without warning, the crab stole Ali’s sock.","The crab moved.","There was a crab.","The unexpected opening engages readers."),q("Rewrite with a different start.","At sunset, our dhoni reached home.","Our dhoni reached home at sunset.","Dhoni home reached.","At sunset moves the time phrase first.")],
 [q("A story character cannot find her library book. What is the complication?","the missing book","the library building","the character’s name","The missing book creates the problem."),q("Which event could resolve a torn sail?","The children patch the cloth.","The wind grows stronger.","The boat leaves without it.","Patching fixes the sail."),q("Choose the sequence with problem and solution.","Net tears — friends mend it — boat leaves safely","Boat leaves — sun shines — fish swim","Friends laugh — lunch begins — bell rings","The first sequence contains complication and resolution."),q("What makes this a satisfying ending? ‘At last, the lost chick returned to its nest.’","the main problem is solved","a new problem begins","the setting disappears","The lost chick is safe."),q("Which middle event raises a simple problem?","A wave washes away the picnic mat.","The family reaches the beach.","Everyone goes home happily.","The wave creates the complication.")],
 [q("Which sentence includes useful description?","The silver fish flashed beneath clear water.","The fish was there.","Fish beneath.","Colour and water details create a picture."),q("Choose an adjective for a rough sea.","stormy","quietly","sail","Stormy describes the sea."),q("Which action shows a character is excited?","She claps and runs toward the boat.","She sits without moving.","She closes her eyes to sleep.","Clapping and running show excitement."),q("Replace went with a precise verb.","hurried","nice","blue","Hurried gives a clearer action."),q("Which dialogue suits a child finding a pearl?","‘Look what I found!’ Mariyam cried.","‘The sky is a room,’ said the fish.","‘Because and then,’ Ali replied.","The first line fits the discovery.")],
 [q("Which fact belongs in a report about mangroves?","Mangrove roots grow in wet, salty ground.","Mangroves are the best plants ever.","I dreamed of a dancing root.","The first line is factual."),q("Select a suitable report title.","Mangroves of the Maldives","My Wild Saturday","Please Save My Snack","The title clearly names the topic."),q("Which sentence defines a dhoni?","A dhoni is a traditional Maldivian boat.","I rode a dhoni yesterday.","The dhoni was my favourite.","The first sentence defines it."),q("Put facts under the correct subheading: ‘It carries passengers.’","Uses","Habitat","Opinion","Carrying passengers is a use."),q("Choose an objective report closing.","Dhonis remain important for island travel.","I think every dhoni is beautiful.","What a funny trip!","The first line summarizes information.")],
 [q("Which opinion includes a reason?","Our class needs more shade because afternoons are hot.","Shade is good.","Afternoons happen.","Because introduces support."),q("Find the opinion rather than a fact.","Beach clean-ups are the best school activity.","The beach has sand.","A bag holds litter.","Best expresses a judgement."),q("Choose a respectful disagreement.","I understand, but I prefer a different plan.","You are completely wrong.","Stop talking now.","The first response is respectful."),q("What evidence supports planting a palm?","It will provide shade near the playground.","I like green.","Palms sound nice.","Shade is a relevant practical reason."),q("Which closing restates an opinion?","Therefore, our class should reuse paper.","First, fold the paper.","Paper comes in many colours.","Therefore returns to the viewpoint.")],
 [q("Choose the first step in explaining how rain forms.","Water warms and rises.","Rain falls into puddles.","Children open umbrellas.","Warming begins the simple process."),q("Which connective shows the next stage?","then","although","perhaps","Then marks sequence."),q("Complete: ‘The sun heats water, so ___.’","some water rises as vapour","the moon becomes a boat","sand turns into coral","Heating can cause evaporation."),q("A clear explanation answers which question?","How or why does it happen?","Who is the funniest?","Which story is best?","Explanations show how or why."),q("Choose the logical process order.","heat — rise — cool — rain","rain — cool — heat — rise","cool — rain — rise — heat","The first sequence is logical.")],
 [q("Where is a comma needed?","After lunch, we read outside.","After, lunch we read outside.","After lunch we, read outside.","The comma follows the opening phrase."),q("Choose the correctly punctuated list.","We packed water, fruit and towels.","We packed, water fruit and towels.","We packed water fruit, and towels.","Commas separate list items."),q("Which apostrophe shows Ali owns the cap?","Ali’s cap","Alis cap","Alis’ cap","Ali’s shows ownership."),q("Pick the contraction for do not.","don’t","dont","do’nt","Don’t replaces the missing o."),q("Which line uses speech punctuation most clearly?","‘Come aboard,’ called Hassan.","Come aboard called Hassan.","‘Come aboard called’ Hassan.","The spoken words are enclosed and separated.")],
 [q("Read: ‘The reef club made signs, placed bins and spoke at assembly. By Friday, less litter lay near the jetty.’ What changed?","The jetty area became cleaner.","The club stopped meeting.","More litter reached the sea.","Less litter means a cleaner area.","The reef club made signs, placed bins and spoke at assembly. By Friday, less litter lay near the jetty."),q("Which action most likely caused the improvement?","placing bins and sharing reminders","painting the classroom wall","counting library books","The actions directly address litter."),q("Choose a heading for the club’s actions.","Our Clean-Jetty Plan","Kinds of Reef Fish","A Lost Lunch Box","The heading matches the work."),q("Which sentence summarizes the result?","A simple class plan reduced litter near the jetty.","The signs used blue paint.","Friday came after Thursday.","The first line captures action and result."),q("How could the pupils present their result visually?","make a before-and-after chart","write an unrelated story","hide the litter count","A chart can show change.")],
 [q("Two texts describe island travel. One is a recount and one is a report. What differs?","their purpose and structure","the English alphabet","the meaning of island","The text types serve different purposes."),q("Which feature identifies the report?","facts arranged under headings","events told with I and yesterday","a problem solved by characters","Headings organize report facts."),q("Which feature identifies the recount?","past events in time order","definitions under subheadings","steps using command verbs","Recounts retell experiences."),q("Select the strongest supported opinion.","The school should add a refill tap because it reduces plastic bottles.","Refill taps are nice.","Everyone must agree with me.","The reason directly supports the proposal."),q("Which response combines Level 4 reading and writing skills?","Compare the texts, note a key difference, then explain it in a paragraph.","Copy every word without reading.","Choose a picture and stop.","The task integrates comparison and explanation.")],
];

export const LEVEL4_DICTATION_WORDS=[
 ["help","sail","play","teach"],["coat","shelf","ground","beam"],["happy","pack","untied","reread"],["care","fear","quick","paint"],["clean","head","beach","dream"],
 ["topic","again","greet","agree"],["poster","bold","photo","north"],["cloud","busy","clean","detail"],["both","ending","events","chart"],["food","group","bold","order"],
 ["theme","clue","close","tuna"],["after","beside","action","sudden"],["book","patch","solve","chick"],["silver","stormy","claps","hurry"],["roots","title","dhoni","uses"],
 ["shade","best","prefer","paper"],["water","then","vapour","why"],["comma","fruit","owner","speech"],["signs","bins","result","change"],["report","facts","recount","reason"],
] as const;

export function level4QuizQuestion(set:number,pos:number):CurriculumQuestion&{passage?:string}{
 const item=LEVEL4_QUIZ_SETS[set]?.[pos];if(!item)throw new Error(`Missing Level 4 quiz item ${set+1}.${pos+1}`);
 return {...item,token:`L4-${set}-${pos}`};
}
