import type {CurriculumQuestion} from "./curriculum.ts";

type Item=Omit<CurriculumQuestion,"token">;
const q=(prompt:string,correct:string,wrong1:string,wrong2:string,explanation:string,audioText?:string):Item=>({prompt,options:[correct,wrong1,wrong2],answer:0,explanation,audioText});

const RAW_LEVEL1_QUIZ_SETS:Item[][]=[
 [q("Find the big letter A.","A","M","S","This is A.","A"),q("Which picture begins with A?","apple","ball","cat","Apple begins with A."),q("Listen for one letter. Tap what you hear.","B","D","P","You heard B.","B"),q("A red apple is hiding. Which card shows it?","apple","banana","sea","The apple is red."),q("Match the ball to its first letter.","B","F","L","Ball begins with B.")],
 [q("Point to uppercase C.","C","G","O","This is uppercase C.","C"),q("The cat needs its letter. Choose it.","C","T","H","Cat begins with C."),q("Hear the letter and touch its card.","D","B","T","You heard D.","D"),q("Which animal says woof?","dog","cat","fish","A dog says woof."),q("Choose the picture that starts like dog.","dog","egg","apple","Dog starts with D.")],
 [q("Show the teacher letter E.","E","F","L","This is E.","E"),q("Which food starts with E?","egg","fish","juice","Egg starts with E."),q("A letter sound is playing. Find F.","F","V","S","You found F.","F"),q("Tap the animal that swims.","fish","lion","rabbit","A fish swims."),q("Follow the bubbles to the F picture.","fish","gift","house","Fish begins with F.")],
 [q("Pick the capital letter G.","G","C","Q","This is G.","G"),q("Which present begins with G?","gift","key","book","Gift begins with G."),q("Listen carefully and choose H.","H","N","K","You heard H.","H"),q("Where can a family live?","house","nest","sea","A family can live in a house."),q("Help H find its picture friend.","house","island","juice","House begins with H.")],
 [q("Touch the tall letter I.","I","J","T","This is I.","I"),q("Which place begins with I?","island","home","lagoon","Island begins with I."),q("The speaker says J. Which one is J?","J","G","U","You heard J.","J"),q("Choose the drink in a box.","juice","water","coconut","This is juice."),q("Sail to the picture that begins with J.","juice","key","lion","Juice begins with J.")],
 [q("Find K among the three letters.","K","R","X","This is K.","K"),q("What can open a lock?","key","pencil","shell","A key opens a lock."),q("Catch the letter L when you hear it.","L","I","T","You heard L.","L"),q("Which animal has a mane?","lion","rabbit","turtle","A lion has a mane."),q("Join L to the right animal.","lion","moon","nest","Lion begins with L.")],
 [q("Choose uppercase M.","M","W","N","This is M.","M"),q("What shines at night?","moon","sun","starfish","The moon shines at night."),q("Listen once, then point to N.","N","M","H","You heard N.","N"),q("Where does a bird keep its eggs?","nest","house","bag","Eggs can be in a nest."),q("Which picture belongs beside N?","nest","octopus","palm","Nest begins with N.")],
 [q("Spot the round letter O.","O","Q","D","This is O.","O"),q("Which sea animal has eight arms?","octopus","fish","turtle","An octopus has eight arms."),q("Hear P and select the matching card.","P","B","R","You heard P.","P"),q("What tall tree grows coconuts?","palm","mango","flower","A palm grows coconuts."),q("Guide P to its island picture.","palm","queen","rabbit","Palm begins with P.")],
 [q("Tap the letter Q.","Q","O","G","This is Q.","Q"),q("Who may wear a crown?","queen","teacher","mother","A queen may wear a crown."),q("A voice says R. Find R.","R","P","B","You heard R.","R"),q("Which animal has long ears?","rabbit","lion","cat","A rabbit has long ears."),q("Choose R's picture partner.","rabbit","sun","turtle","Rabbit begins with R.")],
 [q("Point at uppercase S.","S","Z","C","This is S.","S"),q("What bright object is in the daytime sky?","sun","moon","rain","The sun is bright."),q("Listen for T, then tap it.","T","F","I","You heard T.","T"),q("Which sea animal carries a shell?","turtle","dolphin","fish","A turtle carries a shell."),q("Match T with its swimming friend.","turtle","umbrella","van","Turtle begins with T.")],
 [q("Find the letter U.","U","V","Y","This is U.","U"),q("What keeps rain off your head?","umbrella","cap","book","An umbrella keeps rain off."),q("The sound is V. Choose V.","V","U","W","You heard V.","V"),q("Which one travels on a road?","van","dhoni","fish","A van travels on a road."),q("Park V beside its picture.","van","wave","x-ray","Van begins with V.")],
 [q("Touch uppercase W.","W","M","V","This is W.","W"),q("What rolls onto the beach?","wave","boat","rain","A wave rolls onto the beach."),q("Listen to X and find it.","X","K","Y","You heard X.","X"),q("Which picture can show bones?","x-ray","map","book","An x-ray can show bones."),q("Connect X to the correct picture clue.","x-ray","yo-yo","zebra","X is for x-ray.")],
 [q("Select the capital letter Y.","Y","V","T","This is Y.","Y"),q("Which toy moves on a string?","yo-yo","ball","top","A yo-yo moves on a string."),q("Hear the final alphabet letter and choose it.","Z","S","X","You heard Z.","Z"),q("Which animal has black-and-white stripes?","zebra","lion","rabbit","A zebra has stripes."),q("Send Z to its animal picture.","zebra","apple","fish","Zebra begins with Z.")],
 [q("A friend arrives. What can you say?","hello","goodbye","no","Say hello when someone arrives."),q("Someone is leaving. Choose a kind word.","goodbye","hello","yes","Say goodbye when someone leaves."),q("Listen to the polite word and tap it.","please","no","sad","You heard please.","please"),q("A friend helps you. What do you say?","thank you","sit","jump","Say thank you after help."),q("You need help with a bag. Pick the useful word.","help","goodbye","happy","Say help when you need it.")],
 [q("Agree with a green tick.","yes","no","goodbye","Yes means you agree."),q("Which word goes with a red cross?","no","yes","hello","No does not agree."),q("Hear a feeling word. Find happy.","happy","sad","tired","You heard happy.","happy"),q("Which face has a smile?","happy","sad","sleeping","A smiling face is happy."),q("A child has one tear. Choose the feeling.","sad","happy","fine","The child feels sad.")],
 [q("Your teacher says, ‘Sit.’ Which picture follows it?","sit","stand","jump","Sit means rest on a seat.","sit"),q("Choose the child standing on two feet.","stand","sit","sleep","This child is standing."),q("Listen to one action and tap it.","clap","read","drink","You heard clap.","clap"),q("Which action lifts both feet from the ground?","jump","sit","look","Jump lifts you from the ground."),q("A crab says, ‘Run!’ What should the child do?","run","sleep","stand","Run means move fast.")],
 [q("Which picture shows a school book?","book","bag","chair","This is a book."),q("Find the tool used to draw a line.","pencil","key","cup","A pencil draws a line."),q("Hear ‘bag’ and choose the matching picture.","bag","book","home","You heard bag.","bag"),q("Where can the pencil and book go?","bag","sea","tree","School things can go in a bag."),q("Tap the place where you live.","home","school","reef","Home is where you live.")],
 [q("Point to the person speaking when they say ‘I’.","I","you","they","I means the speaker."),q("A friend stands beside you. Which word names the friend?","you","I","me","You names the person being spoken to."),q("Listen for ‘name’ and touch its tag.","name","book","home","You heard name.","name"),q("Complete the greeting idea: My ___ is Ali.","name","bag","fish","People call you by your name."),q("Which pair can be in a family?","mum and dad","book and pen","sun and sea","Mum and dad are family words.")],
 [q("Tap the body part used to see.","eyes","ears","nose","Eyes help us see."),q("Which body part hears a dhoni bell?","ears","mouth","feet","Ears help us hear."),q("Listen for ‘nose’ and point to it.","nose","eye","hand","You heard nose.","nose"),q("What can your mouth do?","say hello","see a fish","hear music","A mouth can say hello."),q("Count the eyes on one face.","two","one","three","A face usually has two eyes.")],
 [q("Three apples sit in a basket. Choose the number.","3","2","5","There are three apples."),q("Find the number five among the cards.","5","8","2","This is 5."),q("Listen to ‘two’ and tap its numeral.","2","1","4","You heard two.","two"),q("One turtle meets one turtle. How many turtles now?","2","1","3","One and one make two."),q("Which group shows one shell?","one shell","three shells","five shells","This group has one shell.")],
 [q("Which two words rhyme when you hear them?","cat and hat","cat and dog","hat and sun","Cat and hat rhyme.","cat hat"),q("Clap the word ‘coconut’. How many big beats?","three","one","five","Co-co-nut has three beats."),q("Listen and choose the word beginning like ball.","bag","cat","dog","Bag and ball begin with B.","ball bag"),q("Follow this island instruction: Point to the fish.","fish","palm","sun","You followed the instruction.","Point to the fish"),q("A child needs water. Which picture helps?","water","book","ball","Water meets the need for a drink.")],
];

const ALPHABET_FOUNDATION:Item[][]=[
 [q("Welcome A, B, C and D. Which card is A?","A","C","D","You found A.","A"),q("The apple needs its beginning letter.","A","B","C","Apple begins with A."),q("Listen for B among these letters.","B","D","A","You heard B.","B"),q("Which animal begins with C?","cat","dog","fish","Cat begins with C."),q("Send D to the picture that says woof.","dog","cat","bird","Dog begins with D.")],
 [q("Meet E, F, G and H. Point to E.","E","F","H","This is E.","E"),q("Choose the food whose name begins with E.","egg","fish","gift","Egg begins with E."),q("A voice makes the letter F. Catch it.","F","H","E","You heard F.","F"),q("Which wrapped object starts with G?","gift","book","key","Gift begins with G."),q("Help H find a place where a family lives.","house","island","nest","House begins with H.")],
 [q("From I, J, K and L, select I.","I","J","L","This is I.","I"),q("Sail to the place beginning with I.","island","lagoon","home","Island begins with I."),q("Hear J and touch its shape.","J","I","K","You heard J.","J"),q("What opens a lock and begins with K?","key","juice","lion","Key begins with K."),q("Find the animal whose name launches with L.","lion","rabbit","turtle","Lion begins with L.")],
 [q("M, N, O and P are swimming by. Tap M.","M","N","P","This is M.","M"),q("Which night object begins with M?","moon","nest","sun","Moon begins with M."),q("Listen closely for N.","N","M","O","You heard N.","N"),q("Choose the eight-armed O animal.","octopus","fish","crab","Octopus begins with O."),q("Which island tree begins with P?","palm","mango","coconut","Palm begins with P.")],
 [q("Look at Q, R, S and T. Find Q.","Q","R","S","This is Q.","Q"),q("Who wears a crown and begins with Q?","queen","teacher","mother","Queen begins with Q."),q("The speaker says R. Which card matches?","R","Q","T","You heard R.","R"),q("Point to the bright S object in the sky.","sun","moon","rain","Sun begins with S."),q("Which shell-backed swimmer starts with T?","turtle","fish","dolphin","Turtle begins with T.")],
 [q("U, V and W ride a wave. Touch U.","U","V","W","This is U.","U"),q("What rain cover begins with U?","umbrella","cap","bag","Umbrella begins with U."),q("Listen once for the letter V.","V","W","U","You heard V.","V"),q("Choose the road vehicle beginning with V.","van","boat","dhoni","Van begins with V."),q("What moving sea water starts with W?","wave","rain","reef","Wave begins with W.")],
 [q("The alphabet ends with X, Y and Z. Select X.","X","Y","Z","This is X.","X"),q("Which picture beginning with X can show bones?","x-ray","map","book","X is for x-ray."),q("Hear Y and choose its card.","Y","X","Z","You heard Y.","Y"),q("Find the string toy beginning with Y.","yo-yo","ball","top","Yo-yo begins with Y."),q("Which striped animal completes Z?","zebra","lion","rabbit","Zebra begins with Z.")],
];

const COMPLETE_FOUNDATION:Item[][]=[
 [q("A banana is yellow. Choose its colour.","yellow","red","blue","The banana is yellow."),q("Find the object coloured red.","apple","sea","banana","The apple is red."),q("Listen for the colour of the sea.","blue","yellow","red","The sea is blue.","blue"),q("Which picture shows a round toy?","ball","book","pencil","A ball is round."),q("Touch the long tool used for drawing.","pencil","apple","cup","A pencil draws.")],
 [q("A small reef fish needs its home. Pick the sea place.","reef","house","school","A reef is a fish home."),q("Which island object grows on a palm?","coconut","book","ball","A coconut grows on a palm."),q("Hear the beach word and select sand.","sand","rain","home","You heard sand.","sand"),q("What carries people across the lagoon?","dhoni","van","chair","A dhoni travels on water."),q("Choose the animal walking sideways.","crab","turtle","dolphin","A crab walks sideways.")],
 [q("A thirsty child points to one need. What helps?","water","pencil","ball","Water helps thirst."),q("Which face may need rest?","tired","happy","fine","A tired child needs rest."),q("Listen: ‘I am hungry.’ Pick what can help.","food","book","key","Food helps hunger.","I am hungry"),q("A child cannot lift a bag. Which word can they use?","help","goodbye","no","The child can ask for help."),q("Choose the kind response to ‘Are you okay?’","yes","pencil","jump","Yes is a response.")],
 [q("Trace the first letter in the name Ali.","A","L","I","Ali begins with A."),q("Which name tag could belong to Mariyam?","Mariyam","book","happy","Mariyam is a name."),q("Listen to ‘My name is Shifa.’ What is the name?","Shifa","my","is","The name is Shifa.","My name is Shifa"),q("Find the word seen on an exit sign.","EXIT","FISH","BALL","EXIT is environmental print."),q("A green traffic sign says GO. Which card matches?","GO","NO","ME","The sign says GO.")],
 [q("Tap once for the word fish. How many beats?","one","two","three","Fish has one beat."),q("Clap coconut slowly. Count its parts.","three","one","four","Co-co-nut has three parts."),q("Listen for the pair that rhymes.","sun and fun","sun and fish","fun and cat","Sun and fun rhyme.","sun fun"),q("Which words end with the same sound?","cat and hat","cat and dog","hat and sea","Cat and hat rhyme."),q("Complete the chant: One, two, touch your ___.","shoe","book","sun","Two and shoe rhyme.")],
];

export const LEVEL1_QUIZ_SETS:Item[][]=[...ALPHABET_FOUNDATION,...RAW_LEVEL1_QUIZ_SETS.slice(13),...COMPLETE_FOUNDATION];

export function level1QuizQuestion(set:number,pos:number):CurriculumQuestion{
 const item=LEVEL1_QUIZ_SETS[set]?.[pos];
 if(!item)throw new Error(`Missing Level 1 quiz item ${set+1}.${pos+1}`);
 return {...item,token:`L1-${set}-${pos}`};
}
