import type {CurriculumQuestion} from "./curriculum.ts";
type Item=Omit<CurriculumQuestion,"token">;
const q=(prompt:string,correct:string,wrong1:string,wrong2:string,explanation:string,audioText?:string):Item=>({prompt,options:[correct,wrong1,wrong2],answer:0,explanation,audioText});

export const LEVEL2_QUIZ_SETS:Item[][]=[
 [q("Listen to a classroom word. Choose what you hear.","book","bag","chair","You heard book.","book"),q("Aminath says, ‘Hello. My ___ is Aminath.’","name","friend","teacher","Name completes the introduction."),q("Complete the short line: I ___ Hassan.","am","is","are","I am Hassan."),q("Hear the school object and find its picture.","pencil","book","bag","You heard pencil.","pencil"),q("Which reply fits ‘Hello, my name is Ali’?","Hello, Ali!","Goodbye, chair!","Under the bag.","A friendly greeting fits.")],
 [q("A feeling word is playing. Tap it.","happy","book","under","You heard happy.","happy"),q("Which face matches ‘I feel sad’?","a crying face","a smiling face","a sleeping cat","A crying face can show sadness."),q("Finish Mariyam’s line: I am ___.","fine","chair","pencil","I am fine is a clear reply."),q("Listen for the child who needs rest.","tired","happy","good","You heard tired.","tired"),q("Hassan gets a gift. How may he feel?","happy","sad","under","A gift may make Hassan happy.")],
 [q("Hear a short-a word and select it.","cat","sun","pig","You heard cat.","cat"),q("Which word rhymes with cat?","mat","dog","fin","Cat and mat rhyme."),q("Complete the word family: m_t.","mat","cot","cut","A makes mat."),q("Listen: a hat sits on the sand. Find the focus word.","hat","hen","hop","You heard hat.","hat"),q("Which short-a word names a place to wipe feet?","mat","map","cap","A mat lies on the floor.")],
 [q("A short-e word is spoken. Catch it.","hen","sun","cat","You heard hen.","hen"),q("Which word ends like hen?","pen","pig","pot","Hen and pen share -en."),q("Fill the missing vowel: b_d.","bed","bad","bud","E makes bed."),q("Listen for something used to write.","pen","pin","pan","You heard pen.","pen"),q("Which short-e word is a colour?","red","blue","pink","Red has a short e sound.")],
 [q("Listen to the short-i word.","pig","dog","cat","You heard pig.","pig"),q("Which word belongs to the -in family?","fin","fun","fan","Fin ends with -in."),q("Complete the action word: s_t.","sit","sat","set","I makes sit."),q("Hear the small pointed object.","pin","pen","pan","You heard pin.","pin"),q("Which body word uses short i?","lip","leg","hand","Lip has a short i sound.")],
 [q("A short-o word is playing. Find it.","dog","pig","sun","You heard dog.","dog"),q("Which word rhymes with dog?","log","lip","bed","Dog and log rhyme."),q("Complete the cooking word: p_t.","pot","pet","pit","O makes pot."),q("Listen to the word for the highest part.","top","tap","tip","You heard top.","top"),q("Which action word has short o?","hop","run","sit","Hop has a short o sound.")],
 [q("Hear the short-u word and tap it.","sun","hen","dog","You heard sun.","sun"),q("Which vehicle rhymes with us?","bus","van","boat","Bus rhymes with us."),q("Complete the drinking object: c_p.","cup","cap","cop","U makes cup."),q("Listen for the fast action.","run","sit","hop","You heard run.","run"),q("Which word means happy play?","fun","fin","fan","Fun means happy play.")],
 [q("Listen for a tiny sight word.","the","we","can","You heard the.","the"),q("Choose the word in ‘The fish is blue.’","the","on","am","The begins the sentence."),q("Complete: A shell ___ in the sand.","is","in","it","Is completes the sentence."),q("Hear the place word from ‘in the bag’.","in","is","it","You heard in.","in"),q("Which card completes ‘The book is ___ the table’?","on","the","a","On shows the place.")],
 [q("A speaker says a people word. Find it.","you","my","can","You heard you.","you"),q("Choose the word showing something belongs to me.","my","we","the","My shows belonging."),q("Complete the ability line: I ___ swim.","can","am","in","Can shows ability."),q("Listen for the word meaning the speakers together.","we","you","my","You heard we.","we"),q("Which sentence is a clear guided line?","We can read.","Can we the.","Read my is.","We can read is complete.")],
 [q("Listen for the object used with ‘an’.","egg","book","pencil","We say an egg.","egg"),q("Which phrase sounds right?","an egg","a egg","an book","Use an before egg."),q("Complete: ___ island.","an","a","on","Use an before island."),q("Hear the article used before book.","a","an","in","You heard a.","a"),q("Pick the correct pair.","a pencil","an pencil","a octopus","Use a before pencil.")],
 [q("Listen for the place word.","under","on","in","You heard under.","under"),q("A shell is inside a box. Which word tells its place?","in","on","under","In means inside."),q("Complete: The book is ___ the chair.","on","in","under","On means touching the top."),q("Hear the location in ‘on the palm mat’.","on","in","under","You heard on.","on"),q("Where is a crab below a boat?","under the boat","on the boat","in the boat","Below the boat means under it.")],
 [q("Listen for the word that means the big form of a letter.","upper","small","ending","Upper means the big letter form.","upper"),q("Which line starts correctly?","The fish swims.","the fish swims.","THE FISH swims.","A sentence begins with a capital."),q("Hear the word for an ending mark.","stop","comma","question","A full stop ends a statement.","stop"),q("Hear the tiny name for the ending point.","dot","capital","label","A full stop looks like a dot.","dot"),q("Choose the sentence with a capital and full stop.","A crab runs.","a crab runs.","A crab runs","This sentence starts and ends correctly.")],
 [q("Listen to the first story-order word.","first","then","last","You heard first.","first"),q("A turtle wakes. What may happen next?","Then it swims.","First it already ended.","Under it blue.","Then introduces the next event."),q("Complete: First I open the book. ___ I read.","Then","Under","An","Then continues the order."),q("Hear the word used when telling a story again.","retell","label","draw","You heard retell.","retell"),q("Which two cards show a clear order?","first — then","under — an","book — happy","First and then show order.")],
 [q("Listen to the word placed under a picture.","label","draw","story","You heard label.","label"),q("Which label belongs under a palm picture?","palm","fish","book","Palm names the picture."),q("Complete the drawing direction: Draw the ___.","sea","read","then","Sea names something to draw."),q("Hear the action used to make a picture.","draw","read","listen","You heard draw.","draw"),q("Which picture-and-word pair matches?","island — 🏝️","island — ✏️","island — 🐟","The island picture matches island.")],
 [q("Listen to the reading action.","read","say","look","You heard read.","read"),q("Which short line tells about a dolphin?","The dolphin swims.","Dolphin the quickly.","Under dolphin an.","The first line is complete."),q("Complete the sentence: I can ___.","look","under","happy","Look completes the ability sentence."),q("Hear the action done with your voice.","say","look","check","You heard say.","say"),q("What should you do after writing a short line?","check it","hide it","mix it","Checking helps find mistakes.")],
 [q("Listen for the animal in the mini story.","crab","palm","book","You heard crab.","crab"),q("A crab finds a hat. What happens first?","The crab finds the hat.","The hat says goodbye.","The sea reads a book.","The finding event begins the story."),q("Complete the picture-story line: The crab is ___.","red","pencil","under","Red describes the crab."),q("Hear the place where the funny story happens.","beach","chair","bag","You heard beach.","beach"),q("Which ending fits the tiny story?","The crab waves goodbye.","First before the crab.","An under happy.","The goodbye event can end the story.")],
 [q("Listen to the key word in Aminath’s introduction.","name","under","full stop","The key word is name.","name"),q("Which response continues ‘My name is Aminath’?","Hello, Aminath!","Aminath under.","An Aminath.","The greeting continues the conversation."),q("Complete Hassan’s line: I am ___.","Hassan","pencil","on","A name completes the introduction."),q("Hear an action that shows happiness.","smile","cry","sleep","A smile can show happiness.","smile"),q("Which short exchange makes sense?","Hello! — Hello!","Book! — Under!","Happy! — Pencil!","The greetings match.")],
 [q("Listen for the classroom seat.","chair","sun","fish","You heard chair.","chair"),q("Which line uses under correctly?","The bag is under the chair.","The bag under is chair.","Under bag the chair is.","The first sentence has clear order."),q("Complete the polite request: ___ help me.","Please","Happy","Pencil","Please begins a polite request."),q("Hear the answer to ‘Can you read?’","yes","book","under","You heard yes.","yes"),q("Which classroom direction has two clear parts?","Open the book and look.","Book open the under.","Happy pencil and.","The first direction is clear and simple.")],
 [q("Listen for the beach object in this review.","shell","book","chair","You heard shell.","shell"),q("Where is the fish if it is inside the reef cave?","in the cave","on the cave","under the sea","In means inside."),q("Complete with a sight word: ___ can swim.","We","On","An","We can swim is complete."),q("Hear a word about the beginning of a line.","start","under","stop","A sentence starts with a capital.","start"),q("Which line has the best punctuation?","My bag is red.","my bag is red.","My bag is red","The first line has a capital and full stop.")],
 [q("Listen to the focus word in the island sentence.","palm","pen","pig","You heard palm.","palm"),q("Which sentence matches a turtle picture?","The turtle is in the sea.","The pencil is happy.","An chair can swim.","The first sentence matches a turtle."),q("Complete the story order: First the sun rises. ___ school starts.","Next","Under","A","Next adds the following event."),q("Hear the final review word.","check","draw","under","You heard check.","check"),q("Choose the line that combines Level 2 skills.","A fish is in the blue sea.","fish blue in sea a","An fish under blue","The first line is complete and meaningful.")],
];

export function level2QuizQuestion(set:number,pos:number):CurriculumQuestion{
 const item=LEVEL2_QUIZ_SETS[set]?.[pos];
 if(!item)throw new Error(`Missing Level 2 quiz item ${set+1}.${pos+1}`);
 return {...item,token:`L2-${set}-${pos}`};
}
