import type {CurriculumQuestion} from "./curriculum.ts";
const D=[
 ["Source synthesis","synthesis","combining compatible ideas from several sources","A reef chart records rising fish numbers, while a ranger’s interview describes returning habitats. Together, the sources support a fuller explanation of recovery than either source alone. The pupil combines only details that address the same question."],
 ["Precise nuance","nuance","a small but meaningful difference","Calling the lagoon calm suggests still water, while calling it peaceful also suggests a feeling. Mariyam studies this nuance before selecting the word that expresses her exact meaning in a descriptive paragraph."],
 ["Rhetorical appeals","appeal","a method used to influence an audience","A school reef poster combines a verified litter count, a photograph of a trapped turtle and a message from a respected island guide. Each element influences readers in a different but understandable way."],
 ["Source credibility","credible","believable because a source is informed and dependable","For tide safety, Hassan compares an anonymous message with information from the national weather service and an experienced harbour officer. He chooses the sources whose knowledge and responsibility make them credible."],
 ["Corroborating evidence","corroborate","confirm a detail by finding matching evidence","A chart reports fewer plastic bottles near the jetty. Weekly photographs and the caretaker’s records show the same pattern, so these independent details corroborate the chart’s result."],
 ["Interpreting ambiguity","ambiguity","language that allows more than one meaning","The notice says, ‘Meet the guide by the old boat with binoculars.’ It is unclear who has the binoculars. The class identifies the ambiguity and rewrites the direction so visitors cannot misunderstand it."],
 ["Connotation and denotation","connotation","the feeling or association carried by a word","Both slender and skinny describe a narrow shape, but their connotations differ. In a wildlife report, the writer chooses slender because it describes the heron accurately without adding an unkind judgement."],
 ["Recognising irony","irony","a contrast between what is expected and what happens","Ali proudly carries an umbrella through a bright morning, but the only splash comes when his own water bottle opens inside his bag. The unexpected contrast creates gentle, child-friendly irony."],
 ["Foreshadowing","foreshadow","hint at an event that will occur later","Before the dhoni race begins, the story mentions a loose knot and a strengthening breeze. These details foreshadow the sail problem that appears in the next scene and prepare readers without revealing everything."],
 ["Multiple perspectives","perspective","a particular way of viewing an event","A new harbour rule is welcomed by swimmers, questioned by fishers and explained by safety officers. Comparing each perspective helps pupils understand why one change can affect community members differently."],
 ["Paragraph cohesion","cohesion","clear connections holding ideas together","In Aminath’s report, each paragraph begins from the previous idea. Pronouns, repeated key terms and connectives guide readers from the reef problem to the class action and then to the measured result."],
 ["Clear thesis","thesis","a focused central claim guiding a longer response","After reading three island transport texts, Nihan writes that reliable ferries improve education, health access and family connections. Every paragraph then develops one part of this clear thesis with relevant evidence."],
 ["Qualified claims","qualify","limit a statement so it remains accurate","Instead of claiming that every reef recovered, Sara writes that several monitored areas showed improvement during calm months. The added limits qualify the claim and prevent the evidence from being overstated."],
 ["Evidence evaluation","evaluate","judge quality and relevance using clear criteria","Two articles discuss beach erosion. The class evaluates whether each uses recent observations, knowledgeable speakers and details connected to the question before deciding which evidence deserves greater weight."],
 ["Formal register","register","a language style suited to situation and audience","A message to a friend begins casually, while a letter to the island council uses respectful greetings, complete explanations and careful word choices. The formal register matches the public audience."],
 ["Simple citations","citation","a brief acknowledgement of where information came from","In a scaffolded report, the pupil names the weather bulletin and interview used for tide information. This simple citation lets readers recognise the source without requiring a high-school research paper."],
 ["Plot structure","complication","the central difficulty characters must overcome","A story begins with a planned reef visit, but a damaged paddle creates the complication. The children test safe alternatives, borrow a spare and reach the site, forming a complete primary-level plot."],
 ["Multimedia interpretation","multimedia","communication combining forms such as words, sound and images","A conservation video uses narration, a changing map and underwater footage. Pupils compare what each mode contributes and explain how the combined multimedia message becomes clearer."],
 ["Fact and opinion","viewpoint","an opinion shaped and supported by selected facts","The editorial states that shaded waiting areas would improve ferry travel, then uses temperature records and passenger comments. Pupils separate the factual support from the writer’s viewpoint."],
 ["Independent response","response","an organized interpretation supported by relevant details","For the final task, Mariyam compares a story, diagram and interview about mangroves. She plans paragraphs, selects evidence, explains connections and revises her response while using a teacher-provided structure."],
] as const;
export const LEVEL7_QUIZ_SETS=D.map((d,i)=>[
 {prompt:`Integrate the ${d[0].toLowerCase()} passage: which concept best explains the writer’s work?`,passage:d[3],options:[d[1],D[(i+3)%20][1],D[(i+8)%20][1]],answer:0,explanation:`The passage demonstrates ${d[1]}.`},
 {prompt:`Listen for the Level 7 focus word connected to ${d[0].toLowerCase()}.`,options:[d[1],D[(i+5)%20][1],D[(i+11)%20][1]],answer:0,explanation:`You heard ${d[1]}.`},
 {prompt:`Complete the precise definition: ${d[1]} means ___.`,options:[d[2],D[(i+4)%20][2],D[(i+9)%20][2]],answer:0,explanation:`${d[1]} means ${d[2]}.`},
 {prompt:`Which interpretation is most defensible from the ${d[0].toLowerCase()} evidence?`,passage:d[3],options:[`The details apply ${d[1]} accurately.`,`The details reject all reading strategies.`,`The details concern an unrelated science experiment.`],answer:0,explanation:`The cited details directly apply ${d[1]}.`},
 {prompt:`Select the exact concept-and-definition match for ${d[0].toLowerCase()}.`,options:[`${d[1]} — ${d[2]}`,`${D[(i+2)%20][1]} — ${d[2]}`,`${d[1]} — ${D[(i+7)%20][2]}`],answer:0,explanation:`The first pairing is exact.`},
]);
export const LEVEL7_DICTATION_WORDS=D.map(d=>d[1]);
export function level7QuizQuestion(set:number,pos:number):CurriculumQuestion&{passage?:string}{const item=LEVEL7_QUIZ_SETS[set]?.[pos];if(!item)throw new Error(`Missing Level 7 item ${set+1}.${pos+1}`);return {...item,token:`L7-${set}-${pos}`}}
