import type {CurriculumQuestion} from "./curriculum.ts";
type Spec={theme:string;focus:string;meaning:string;example:string;contrast:string;passage:string};
const SPECS:Spec[]=[
 {theme:"Fiction series",focus:"episode",meaning:"one part of a continuing story",example:"The second reef adventure continues Ali’s search for the lost compass.",contrast:"a separate fact sheet",passage:"Ali returned to the harbour with the brass compass. In the earlier story he had found it beneath a fishing net. This time its needle pointed toward a quiet sandbank, so Ali and Mariyam prepared another careful island journey."},
 {theme:"Mood and tone",focus:"mood",meaning:"the feeling a text creates",example:"Empty streets and rattling palms create an uneasy mood.",contrast:"the number of paragraphs",passage:"Clouds rolled across the lagoon and the palms bent low. Aminath hurried along the empty lane while a loose gate tapped behind her. When warm lights appeared at home, the tense mood softened into relief."},
 {theme:"Island reports",focus:"habitat",meaning:"the natural home of a living thing",example:"The report groups turtle habitat facts under a clear heading.",contrast:"a personal joke",passage:"Sea turtles live in warm oceans and visit sandy islands to nest. A report can group these facts under Habitat, Food and Life Cycle. Clear headings help readers locate each kind of information quickly."},
 {theme:"How-and-why explanations",focus:"process",meaning:"a series of changes or actions",example:"The diagram explains how coconut fibre becomes rope.",contrast:"a character’s conversation",passage:"First, dry coconut husks are soaked and beaten. The fibres are separated, twisted and joined into longer strands. This process turns a familiar island material into strong coir rope."},
 {theme:"Narrative problems",focus:"solution",meaning:"the action that resolves a problem",example:"The children repair the leaking model dhoni with wax.",contrast:"the opening description",passage:"Hassan’s model dhoni began leaking during the school race. His team lifted it from the pool and pressed soft wax over the tiny crack. The repaired boat floated safely to the finish."},
 {theme:"Poetry and imagery",focus:"imagery",meaning:"words that help readers picture or sense something",example:"Silver water flickered beneath the moon.",contrast:"a page number",passage:"The poem describes silver water, whispering palms and cool sand beneath bare feet. These sensory details help the reader imagine a peaceful island evening without using difficult figurative analysis."},
 {theme:"Information features",focus:"sidebar",meaning:"a separate box containing extra information",example:"A sidebar adds a quick fact about whale sharks.",contrast:"the story resolution",passage:"The main article explains reef animals. Beside it, a shaded sidebar gives three quick whale-shark facts. A labelled diagram below shows the animal’s fins and spotted body."},
 {theme:"Comparing texts",focus:"contrast",meaning:"showing how two things differ",example:"The recount is personal, whereas the report gives general facts.",contrast:"listing identical details",passage:"One text recounts Mariyam’s first dhoni trip using I and past-tense verbs. Another explains how dhonis are built using headings and factual language. Their shared topic is island boats, but their purposes differ."},
 {theme:"Reader’s theatre",focus:"expression",meaning:"using the voice to show meaning and feeling",example:"Nihan raises his voice when the character calls across the harbour.",contrast:"reading every line in one flat tone",passage:"During reader’s theatre, Nihan pauses before the surprise and speaks loudly when his character calls for help. His group follows the stage directions and changes expression so listeners can understand each feeling."},
 {theme:"Audience language",focus:"audience",meaning:"the people a text or speech is prepared for",example:"A school notice uses clear, respectful language for families.",contrast:"words chosen only for the writer",passage:"The eco-club writes one message for young pupils and another for parents. The pupil poster uses short commands and bright labels. The family notice gives dates, reasons and polite details suited to its audience."},
 {theme:"Charts and tables",focus:"trend",meaning:"a general direction shown by changing data",example:"The table shows beach litter decreasing each week.",contrast:"one decorative colour",passage:"The class counted twelve bags of litter in week one, eight in week two and four in week three. The table reveals a downward trend after new bins and signs were placed near the jetty."},
 {theme:"Cause and effect",focus:"effect",meaning:"what happens because of a cause",example:"Heavy rain flooded the path, so assembly moved indoors.",contrast:"an unrelated description",passage:"Strong rain covered the school path with water. Because pupils could not cross it safely, teachers moved assembly into the hall. The flooded path was the cause; the changed location was the effect."},
 {theme:"Headings and diagrams",focus:"label",meaning:"a word identifying part of a visual",example:"Each label names a part of the mangrove root system.",contrast:"an opinion about the drawing",passage:"A mangrove diagram uses arrows and labels to identify roots, leaves and new shoots. The heading states the topic, while a short caption explains how the roots hold muddy ground together."},
 {theme:"Linking ideas",focus:"however",meaning:"a connective that introduces a contrast",example:"The sea looked calm; however, a strong current moved below.",contrast:"a connective showing only addition",passage:"The morning was bright; however, the harbour master noticed a strong current. Therefore, the children delayed their swim. The connectives show contrast and result clearly."},
 {theme:"Story characters",focus:"trait",meaning:"a quality shown by a character’s choices",example:"Aminath’s careful rescue plan shows patience.",contrast:"the colour of the page",passage:"A crab became trapped inside a plastic cup. Aminath did not rush or pull it roughly. She asked an adult for help and patiently cut the cup away, showing that she is thoughtful and careful."},
 {theme:"Reading strategies",focus:"evidence",meaning:"a detail from a text supporting an answer",example:"The packed raincoat supports the idea that Hassan expected rain.",contrast:"a guess with no text detail",passage:"Hassan checked the grey clouds, packed a raincoat and covered his books. When asked why he expected wet weather, a reader can point to these actions as evidence from the text."},
 {theme:"Descriptive writing",focus:"precise",meaning:"exact and clearly chosen",example:"The scarlet crab scuttled beneath a cracked shell.",contrast:"a vague word such as nice",passage:"Instead of saying the beach was nice, Shifa wrote that warm white sand curved around a clear turquoise lagoon. Precise nouns, verbs and adjectives help readers build a sharper picture."},
 {theme:"Persuasive writing",focus:"reason",meaning:"support explaining why an opinion should be accepted",example:"Refill stations reduce plastic waste, so our school should install one.",contrast:"an unsupported demand",passage:"The reef club asks school leaders to install a refill station. Their letter explains that reusable bottles reduce plastic waste and save families money. These relevant reasons support the request."},
 {theme:"Punctuation choices",focus:"apostrophe",meaning:"a mark showing possession or missing letters",example:"The pupils’ posters hang beside Mariyam’s chart.",contrast:"a comma separating list items",passage:"The editor checks contractions, possession and lists in the class newsletter. She writes don’t with an apostrophe for a missing letter and Mariyam’s to show that the chart belongs to Mariyam."},
 {theme:"Integrated mastery",focus:"conclusion",meaning:"a final idea reached from details",example:"Cleaner water and returning fish show that the reef project helped.",contrast:"a detail copied without interpretation",passage:"Over three months, pupils recorded less litter, clearer water and more small fish near the school reef. They compared tables, photographs and weekly notes before concluding that their protection project was helping."},
];
const wrong=(i:number,n:number)=>SPECS[(i+n)%SPECS.length];
export const LEVEL5_QUIZ_SETS=SPECS.map((s,i)=>[
 {prompt:`Read the ${s.theme.toLowerCase()} passage. Which idea is central?`,passage:s.passage,options:[s.focus,wrong(i,3).focus,wrong(i,7).focus],answer:0,explanation:`The passage develops ${s.focus}.`},
 {prompt:`Listen for the key word used in the ${s.theme.toLowerCase()} lesson.`,options:[s.focus,wrong(i,4).focus,wrong(i,9).focus],answer:0,explanation:`The key word is ${s.focus}.`},
 {prompt:`Complete the Level 5 meaning: ${s.focus} means ___.`,options:[s.meaning,wrong(i,5).meaning,wrong(i,10).meaning],answer:0,explanation:`${s.focus} means ${s.meaning}.`},
 {prompt:`Which detail best demonstrates ${s.focus} in this Maldivian context?`,passage:s.passage,options:[s.example,s.contrast,wrong(i,6).contrast],answer:0,explanation:s.example},
 {prompt:`Choose the accurate ${s.theme.toLowerCase()} statement.`,options:[`${s.focus}: ${s.meaning}`,`${wrong(i,2).focus}: ${s.meaning}`,`${s.focus}: ${wrong(i,8).meaning}`],answer:0,explanation:`The first pairing is accurate.`},
]);
export const LEVEL5_DICTATION_WORDS=["episode","mood","habitat","process","solve","imagery","sidebar","contrast","express","reader","trend","effect","label","however","trait","proof","precise","reason","mark","result"] as const;
export function level5QuizQuestion(set:number,pos:number):CurriculumQuestion&{passage?:string}{const item=LEVEL5_QUIZ_SETS[set]?.[pos];if(!item)throw new Error(`Missing Level 5 quiz item ${set+1}.${pos+1}`);return {...item,token:`L5-${set}-${pos}`}}
