import type {CurriculumQuestion} from "./curriculum.ts";

type Item=Omit<CurriculumQuestion,"token">&{passage?:string};
const q=(prompt:string,correct:string,wrong1:string,wrong2:string,explanation:string,passage?:string):Item=>({prompt,options:[correct,wrong1,wrong2],answer:0,explanation,passage});

export const LEVEL3_QUIZ_SETS:Item[][]=[
 [q("Aminath shows her shell. Which opening suits her show-and-tell?","This is my shell.","Under blue quickly.","Shell because and.","The first line introduces the object."),q("Follow the first direction: open the book, then point to the title. What comes first?","open the book","point to the title","close the book","Opening happens first."),q("Choose the polite question for a classroom partner.","May I use your ruler?","Ruler me now.","You ruler why?","The first question is clear and polite."),q("Hassan says, ‘Please draw a fish and label its fin.’ What must be labelled?","the fin","the sea","the pencil","The direction names the fin."),q("Which sentence tells listeners what Mariyam brought?","I brought a small coconut.","Small brought I coconut.","Coconut because small.","The complete sentence is ready to share.")],
 [q("Two jobs are given: circle the crab, then colour it red. What is the second job?","colour it red","circle the crab","draw a dhoni","Colouring follows circling."),q("After writing your name, place the card on the desk. Where does the card go?","on the desk","under the desk","inside a bag","The second direction names the desk."),q("Which list shows the order correctly?","wash, dry, sit","sit, wash, dry","dry, sit, wash","The actions follow the spoken order."),q("Nihan hears: ‘Pick up the shell, show your friend, and put it back.’ What happens in the middle?","show your friend","pick up the shell","put it back","Showing is the middle action."),q("Which instruction has exactly two steps?","Stand up and clap twice.","Smile.","Open, read, draw, label and share.","The first direction has two actions.")],
 [q("Which word changes cap into a long-a word?","cape","cup","cap","Magic e makes cape."),q("A boat can glide beside the ___. Choose the magic-e word.","shore","shop","short","Shore has a final silent e."),q("Select the pair in which silent e changes the vowel sound.","kit — kite","hat — hot","sun — sand","Kite grows from kit with silent e."),q("Which word completes the island line: ‘We ride a ___’ ?","bike","back","book","Bike is a magic-e word and fits the line."),q("Tap the word with the same long-a pattern as game.","name","gum","gem","Name and game share a_e.")],
 [q("Which word begins with the quiet th sound heard in thin?","three","this","tree","Three begins with /th/."),q("Complete the family word: mo__er.","mother","mopper","mower","Th completes mother."),q("A crab hides beneath a cloth. Which word contains th?","cloth","clock","clap","Cloth ends in th."),q("Choose the sentence containing two th words.","That feather is soft.","The fish can swim.","Three boats sail.","That and feather both contain th."),q("Which mouth movement helps make th?","tongue gently between the teeth","lips pressed tightly together","mouth fully closed","The tongue and teeth form th.")],
 [q("Which word has the long oo sound heard in moon?","food","book","foot","Food has long oo."),q("The cook stirs soup with a ___.","spoon","stone","shell","A spoon fits and has long oo."),q("Find the word with the shorter oo sound.","book","room","moon","Book uses short oo."),q("Which line uses a long-oo word correctly?","The moon shines over the reef.","The moon eats a pencil.","Moon the quickly.","The moon can shine over a reef."),q("Sort the pair that shares the vowel sound.","pool — cool","look — moon","food — foot","Pool and cool share long oo.")],
 [q("Which word belongs to the -ake family?","lake","line","look","Lake ends in -ake."),q("Find the member of the -ight family.","light","late","list","Light shares -ight."),q("A red crab sits on a flat ___. Choose the -ock word.","rock","rain","rope","Rock fits the sentence and family."),q("Which two words rhyme?","play — day","fish — boat","boat — book","Play and day rhyme."),q("Change the first sound in sand to h. What word appears?","hand","send","hills","Sand becomes hand.")],
 [q("Which sentence introduces a child clearly?","My name is Ali, and I live on an island.","Ali island because.","Lives my name.","The first sentence gives a name and place."),q("A visitor asks where the library is. Which answer helps?","It is beside the office.","Books are fun.","Yesterday was sunny.","The answer gives the location."),q("Choose the best show-and-tell closing.","Thank you for listening.","My shell blue.","First I start.","The first line closes a short presentation."),q("Which question invites a partner to explain?","How did you make it?","Blue or red?","It is mine.","How asks for an explanation."),q("During a conversation, what should you do while a friend speaks?","listen and wait","talk over the friend","turn away","Listening supports a conversation.")],
 [q("Which word tells how the lagoon looked?","calm","swim","island","Calm describes the lagoon."),q("Complete the description: ‘The ___ parrot sat on the palm.’","green","sang","quickly","Green is an adjective."),q("Pick the adjective in ‘A tiny crab carried a shell.’","tiny","carried","shell","Tiny describes the crab."),q("Which sentence paints the clearest picture?","The bright fish darted past pink coral.","The fish went.","Fish coral the.","Specific describing words create a clear picture."),q("Replace nice with a more exact describing word for sand.","soft","ate","under","Soft describes how sand feels.")],
 [q("Read the picture caption: ‘Children plant a palm beside school.’ What are they planting?","a palm","a book","a boat","The caption names a palm."),q("A map key shows 🏫 = school and ⚓ = harbour. Which symbol marks the harbour?","⚓","🏫","🐟","The anchor symbol marks the harbour."),q("A chart shows three shells on Monday and five on Tuesday. Which day has more?","Tuesday","Monday","both days","Five is more than three."),q("Which title fits a picture sequence about washing hands?","Clean Hands","Fast Dhoni","Coral Colours","The title matches the pictured actions."),q("What does a caption do?","explains a picture","ends every story","lists page numbers","A caption gives information about an image.")],
 [q("Read: ‘First Laila found a seed. Next she planted it. Last a green shoot appeared.’ What happened first?","Laila found a seed.","A shoot appeared.","She watered a tree.","The first sentence begins the sequence.","First Laila found a seed. Next she planted it. Last a green shoot appeared."),q("In the seed story, what happened after planting?","a green shoot appeared","the seed was found","the pot sailed away","The last event follows planting."),q("Which word signals the middle of a retelling?","next","first","title","Next moves the story forward."),q("Choose the best three-part order for a beach picnic.","arrive — eat — clean","clean — arrive — eat","eat — clean — arrive","The events have a sensible beginning, middle and end."),q("Which ending completes a tiny turtle story?","At last, the turtle reached the sea.","First, an egg lay in sand.","Next, it crawled.","At last signals the ending.")],
 [q("Yesterday, Hassan visited the harbour. Which word tells when?","Yesterday","Hassan","harbour","Yesterday gives the time."),q("Select the recount opening.","Last Friday, our class walked to the beach.","Crabs have ten legs.","Please wash the cup.","The first line introduces a past event."),q("Complete the past action: ‘We ___ shells beside the reef.’","found","find","finding","Found tells about the past."),q("Which detail belongs in a personal recount?","I laughed when a crab chased my sandal.","All reefs are underwater habitats.","Mix flour with water.","A personal event belongs in a recount."),q("Pick the closing that shares a feeling.","I felt proud of our clean beach.","Next, pick up litter.","A beach has sand.","The closing reflects on the event.")],
 [q("Which plural names more than one shell?","shells","shell","shelled","Shells means more than one."),q("Complete: ‘One child reads; three children ___.’","read","reads","reading","A plural subject uses read."),q("Choose the correct pair.","one fish — two fish","one fish — two fisheses","one fishes — two fish","Fish can stay the same in the plural."),q("Which sentence agrees correctly?","The boats sail at noon.","The boats sails at noon.","The boat sail at noon.","Plural boats pairs with sail."),q("Change crab to show several.","crabs","crab's","crabes","Add s to make crabs.")],
 [q("Which question fits the answer ‘I live in Addu City’?","Where do you live?","What did you eat?","Why is it blue?","Where asks about place."),q("Aminath says she feels nervous. What kind reply can Hassan give?","I can stand beside you.","That is a red pencil.","Go away now.","The first reply offers support."),q("Choose the answer to ‘When does school begin?’","It begins at eight.","Beside the harbour.","With my sister.","When needs a time answer."),q("Which exchange stays on one topic?","Do you like reading? — Yes, I read every night.","Where is the bag? — Fish swim.","Are you ready? — The palm is tall.","Both lines discuss reading."),q("What question helps clarify a direction?","Should I colour the fin or the tail?","May I tell a joke?","Is the sea salty?","The first question checks the task.")],
 [q("Join the ideas: ‘I wore a hat. The sun was bright.’","I wore a hat because the sun was bright.","Because I wore a hat.","The sun and because.","Because gives the reason."),q("Which part states the reason? ‘We stayed inside because rain fell.’","rain fell","we stayed inside","inside because","The rain explains why."),q("Complete: ‘Ali smiled because ___.’","his kite flew","under the chair","smiled Ali","The clause gives a sensible reason."),q("Choose the complete because sentence.","The class cheered because Mariyam read clearly.","Because the class.","Cheered Mariyam because.","Both parts make a complete idea."),q("Why did the crab hide? Pick the logical cause.","A heron came near.","The crab was orange.","The beach had sand.","A nearby heron could cause hiding.")],
 [q("Which action happens before lunch?","wash your hands","clear the dinner plates","go to sleep","Handwashing can happen before lunch."),q("Complete the order: ‘After the bell rings, we ___.’","enter the classroom","wake before dawn","pack yesterday","Entering can follow the bell."),q("What happens between opening a book and closing it?","reading it","buying a coconut","tying a boat","Reading happens between opening and closing."),q("Choose the clearest three-step instruction.","Fold the paper, draw a sail, then colour it.","Paper sail because blue.","Colour before paper maybe.","The first choice gives three ordered actions."),q("Which time word points to a later action?","after","before","first","After signals something later.")],
 [q("Read: ‘Rifa saw dark clouds. She carried the class books inside.’ How did she probably feel about the books?","careful","sleepy","angry","Her action shows care.","Rifa saw dark clouds. She carried the class books inside before rain fell."),q("What clue shows the turtle is tired?","It rests with its eyes closed.","It races across the sand.","It splashes its friends.","Resting with closed eyes suggests tiredness."),q("A boy gives his umbrella to a friend. Which word describes him?","kind","noisy","empty","Sharing an umbrella is kind."),q("Why might Laila smile after reading aloud?","She is pleased with her reading.","Her book disappeared.","The room is underwater.","A smile can show pride or happiness."),q("Which feeling matches shaky hands before show-and-tell?","nervous","hungry","purple","Shaky hands can show nervousness.")],
 [q("Which title suits facts about reef fish?","Fish of the Reef","The Lost Sandal","How I Felt Yesterday","The title names the information topic."),q("Pick a heading for facts about what turtles eat.","Turtle Food","Funny Endings","My Best Day","The heading groups food facts."),q("Which caption matches a photo of a dhoni at the jetty?","A dhoni waits beside the island jetty.","A bird builds a nest in a palm.","Children read inside the library.","The first caption matches the scene."),q("Where should a reader look for the name of a text?","the title","the final full stop","the first adjective","The title names the whole text."),q("A report has headings ‘Home’, ‘Food’, and ‘Body’. What is it likely about?","an animal","a recount of one day","a greeting card","Those headings organize animal facts.")],
 [q("Which sentence can begin a simple report about dolphins?","Dolphins are mammals that live in the sea.","Yesterday I hugged my bag.","Please open the window.","The line introduces factual information."),q("Choose a fact for a turtle report.","Sea turtles lay eggs on beaches.","Turtles are the funniest animals ever.","I wish every turtle wore a hat.","The first statement is factual."),q("Which heading holds ‘It uses flippers to swim’?","Body and Movement","My Opinion","Funny Problem","The detail describes body and movement."),q("Complete the factual line: ‘A heron ___ fish in shallow water.’","hunts","tell","blue","Hunts makes a factual sentence."),q("Which closing suits a short information report?","These features help the crab live by the shore.","I laughed all day at school.","First, open your lunch box.","The closing sums up the facts.")],
 [q("Read: ‘Nihan’s kite fell into a palm. His sister brought a long stick.’ What is the problem?","The kite is stuck in a palm.","The sister lost a stick.","The palm cannot grow.","The first sentence states the problem.","Nihan flew a kite near home. A gust pushed it into a palm. His sister brought a long stick, and together they freed it."),q("Which event solves the kite problem?","They free it with the stick.","A gust lifts the kite.","Nihan begins flying.","Using the stick resolves the problem."),q("Where does the kite story happen?","near Nihan’s island home","inside a submarine","on a snowy mountain","The passage places it near home."),q("How does teamwork help the characters?","They combine an idea and a tool.","They wait without acting.","They argue about the wind.","The sister's tool helps Nihan."),q("Choose the best retelling.","A kite got stuck, so two children used a stick to free it.","A palm grew beside a house.","A child owned a colourful kite.","The first choice includes problem and solution.")],
 [q("A beach-cleaning chart shows 4 bags on Friday and 7 on Saturday. What does it show?","Saturday had more bags.","Friday had more bags.","Both days had seven.","Seven is greater than four."),q("Which caption matches children sorting cans and bottles?","The eco-club separates items for recycling.","The football team scores a goal.","A cook slices fruit.","The caption matches the pictured action."),q("Read the direction: ‘Draw a route from school to the jetty, then add a key.’ What comes last?","add a key","draw the route","erase the school","Adding the key is second."),q("Which sentence combines an adjective and a place detail?","The small boat rests beside the wooden jetty.","Boat rests.","Beside quickly boat.","Small describes the boat and beside gives place."),q("Complete the mastery check: A clear story has ___.","a beginning, middle and end","only a title","facts under every heading","Stories follow a sequence.")],
];

// Dedicated one-word dictation ensures every Level 3 dictation is unique and no longer than six letters.
export const LEVEL3_DICTATION_WORDS=[
 ["talk","open","ask","show"],["circle","card","order","shell"],["cape","shore","kite","bike"],["three","mother","cloth","teeth"],["food","spoon","book","moon"],
 ["lake","light","rock","hand"],["island","office","thank","listen"],["calm","green","tiny","bright"],["school","anchor","chart","title"],["seed","shoot","next","clean"],
 ["visit","event","found","beach"],["plural","child","fish","boats"],["where","worry","eight","topic"],["reason","rain","smile","heron"],["before","enter","read","fold"],
 ["cloud","tired","kind","proud"],["reef","turtle","dhoni","text"],["report","facts","body","hunts"],["issue","stick","home","team"],["dawn","safe","notes","clear"],
] as const;

export function level3QuizQuestion(set:number,pos:number):CurriculumQuestion&{passage?:string}{
 const item=LEVEL3_QUIZ_SETS[set]?.[pos];
 if(!item)throw new Error(`Missing Level 3 quiz item ${set+1}.${pos+1}`);
 return {...item,token:`L3-${set}-${pos}`};
}
