import fs from "node:fs";
const app=fs.readFileSync(new URL("../app/OceanLearnApp.tsx",import.meta.url),"utf8");
const match=app.match(/const DICTATION_SPEECH=\[(.*?)\];/s);if(!match)throw new Error("Dictation speech profiles missing");
const ages=[...match[1].matchAll(/age:(\d+)/g)].map(m=>Number(m[1])),normalRates=[...match[1].matchAll(/normalRate:([.\d]+)/g)].map(m=>Number(m[1])),slowRates=[...match[1].matchAll(/slowRate:([.\d]+)/g)].map(m=>Number(m[1]));
if(ages.join(",")!=="5,6,7,8,9,10,11")throw new Error("Age ladder must cover ages 5-11");
if(normalRates.length!==7||slowRates.length!==7||normalRates.some((rate,i)=>i>0&&rate<=normalRates[i-1])||slowRates.some((rate,i)=>i>0&&rate<=slowRates[i-1]))throw new Error("Both speech-rate ladders must increase gradually");
if(normalRates.some((rate,i)=>rate-slowRates[i]<.30))throw new Error("Normal and slow playback must have a clearly audible rate gap");
if(slowRates[0]>.35||normalRates[6]>1)throw new Error("Speech boundary rates are not learner appropriate");
if(!app.includes('voice.lang="en-GB"')||!app.includes("FEMALE_VOICE_NAMES")||!app.includes("voice.voice=female"))throw new Error("Dictation player does not prefer a female British-English voice");
if(!app.includes("Hear slower")||!app.includes("slower?profile.slowRate:profile.normalRate")||!app.includes("DictationControls"))throw new Error("Two-level dictation speed controls are missing");
console.log(JSON.stringify({ages,normalRates,slowRates,minimumRateGap:Math.min(...normalRates.map((rate,i)=>rate-slowRates[i])),language:"en-GB",voice:"female preferred",speeds:["Hear","Hear slower"],dictationOnly:true},null,2));
